# Generated by Django 3.2.5 on 2022-04-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.RenameField(
            model_name='productgallery',
            old_name='image',
            new_name='images',
        ),
    ]
