# Generated by Django 3.2.5 on 2022-02-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varitions',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
