# Generated by Django 3.2.5 on 2022-02-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_varitions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varitions',
            new_name='variations',
        ),
    ]
